export enum SocketMessageType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  STREAMER_JOIN_ROOM = 'STREAMER_JOIN_ROOM',
  VIEWER_JOIN_ROOM = 'VIEWER_JOIN_ROOM',
  REQ_OFFER = 'REQ_OFFER',
  SEND_OFFER = 'SEND_OFFER',
  SEND_ANSWER = 'SEND_ANSWER',
}